[CmdletBinding()]
param(
    [string]$SourcePath = "",
    [double]$MinimumRate = 15,
    [double]$RecommendedRate = 17,
    [switch]$NoFail
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($SourcePath)) {
    $SourcePath = Join-Path (Split-Path -Parent $PSScriptRoot) "Assets\Scripts"
}

$sourceRoot = (Resolve-Path $SourcePath).Path
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$excludedDirectoryNames = @("Obsolete", "ThirdParty", "Samples", "Generated")
$violations = [System.Collections.Generic.List[object]]::new()
$moduleStats = @{}
$commentLines = 0
$codeLines = 0
$scannedFiles = 0

function Test-ExcludedPath {
    param([System.IO.FileInfo]$File)

    $relativePath = $File.FullName.Substring($sourceRoot.Length).TrimStart([char[]]"\/")
    $segments = $relativePath -split '[\\/]'
    foreach ($segment in $segments) {
        if ($excludedDirectoryNames -contains $segment) {
            return $true
        }
    }

    return $File.Name -match '(?i)(\.g\.cs$|\.generated\.cs$|\.designer\.cs$)'
}

function Get-NormalizedCommentText {
    param([string]$Text)

    $normalized = $Text.Trim()
    $normalized = $normalized -replace '^[/*\s]+', ''
    $normalized = $normalized -replace '[*/\s]+$', ''
    return $normalized.Trim()
}

function Add-Violation {
    param(
        [string]$Path,
        [int]$Line,
        [string]$Rule,
        [string]$Text
    )

    $violations.Add([pscustomobject]@{
        Path = $Path
        Line = $Line
        Rule = $Rule
        Text = $Text.Trim()
    })
}

function Test-CommentedCode {
    param([string]$Text)

    $codePatterns = @(
        '^\s*(using|namespace)\s+[A-Za-z_]',
        '^\s*(public|private|protected|internal)\s+',
        '^\s*(class|struct|interface|enum|record)\s+',
        '^\s*(if|for|foreach|while|switch|catch|lock)\s*\(',
        '^\s*(return|throw|yield|await)\b',
        '^\s*(Debug|Console)\.[A-Za-z_]+\s*\(',
        '^\s*#(if|elif|else|endif|region|endregion)\b',
        '^\s*[{}]\s*$',
        '^\s*\[[A-Za-z_][^]]*\]\s*$',
        '^\s*[A-Za-z_][\w<>,.?\[\]\s]*\s+[A-Za-z_]\w*\s*(=|;|\()'
    )

    foreach ($pattern in $codePatterns) {
        if ($Text -match $pattern) {
            return $true
        }
    }

    return $false
}

function Read-CSharpFile {
    param([System.IO.FileInfo]$File)

    $relativePath = $File.FullName.Substring($projectRoot.Length).TrimStart([char[]]"\/").Replace('\', '/')
    $moduleRelativePath = $File.FullName.Substring($sourceRoot.Length).TrimStart([char[]]"\/")
    $moduleName = ($moduleRelativePath -split '[\\/]')[0]
    if (-not $moduleStats.ContainsKey($moduleName)) {
        $moduleStats[$moduleName] = [pscustomobject]@{ Comments = 0; Code = 0 }
    }

    $content = Get-Content -LiteralPath $File.FullName -Raw -Encoding UTF8
    $header = (($content -split "`r?`n") | Select-Object -First 10) -join "`n"
    if ($header -match '(?i)<auto-generated|auto generated code|generated by') {
        return
    }

    $script:scannedFiles++
    $inBlockComment = $false
    $inVerbatimString = $false
    $lines = $content -split "`r?`n"

    for ($lineIndex = 0; $lineIndex -lt $lines.Count; $lineIndex++) {
        $line = $lines[$lineIndex]
        $segments = [System.Collections.Generic.List[string]]::new()
        $hasCode = $false
        $index = 0

        while ($index -lt $line.Length) {
            if ($inBlockComment) {
                $endIndex = $line.IndexOf('*/', $index, [System.StringComparison]::Ordinal)
                if ($endIndex -lt 0) {
                    $segments.Add($line.Substring($index))
                    $index = $line.Length
                    continue
                }

                $segments.Add($line.Substring($index, $endIndex - $index))
                $inBlockComment = $false
                $index = $endIndex + 2
                continue
            }

            if ($inVerbatimString) {
                $quoteIndex = $line.IndexOf([char]34, $index)
                if ($quoteIndex -lt 0) {
                    $index = $line.Length
                    continue
                }

                if ($quoteIndex + 1 -lt $line.Length -and $line[$quoteIndex + 1] -eq [char]34) {
                    $index = $quoteIndex + 2
                    continue
                }

                $inVerbatimString = $false
                $index = $quoteIndex + 1
                continue
            }

            if ([char]::IsWhiteSpace($line[$index])) {
                $index++
                continue
            }

            if ($index + 1 -lt $line.Length -and $line[$index] -eq '/' -and $line[$index + 1] -eq '/') {
                $segments.Add($line.Substring($index + 2))
                break
            }

            if ($index + 1 -lt $line.Length -and $line[$index] -eq '/' -and $line[$index + 1] -eq '*') {
                $inBlockComment = $true
                $index += 2
                continue
            }

            $hasCode = $true

            if ($index + 1 -lt $line.Length -and $line[$index] -eq '@' -and $line[$index + 1] -eq [char]34) {
                $inVerbatimString = $true
                $index += 2
                continue
            }

            if ($line[$index] -eq [char]34 -or $line[$index] -eq [char]39) {
                $delimiter = $line[$index]
                $index++
                while ($index -lt $line.Length) {
                    if ($line[$index] -eq [char]92) {
                        $index += 2
                        continue
                    }
                    if ($line[$index] -eq $delimiter) {
                        $index++
                        break
                    }
                    $index++
                }
                continue
            }

            $index++
        }

        if ($hasCode) {
            $script:codeLines++
            $moduleStats[$moduleName].Code++
        }

        if ($segments.Count -eq 0) {
            continue
        }

        if ($line.TrimStart().StartsWith('///')) {
            $previousLineIndex = $lineIndex - 1
            while ($previousLineIndex -ge 0 -and [string]::IsNullOrWhiteSpace($lines[$previousLineIndex])) {
                $previousLineIndex--
            }

            if ($previousLineIndex -ge 0 -and $lines[$previousLineIndex].TrimStart().StartsWith('[')) {
                Add-Violation $relativePath ($lineIndex + 1) "xml-placement" "XML documentation must appear before attributes"
            }
        }

        $normalizedText = Get-NormalizedCommentText ($segments -join ' ')
        if ([string]::IsNullOrWhiteSpace($normalizedText)) {
            continue
        }

        $script:commentLines++
        $moduleStats[$moduleName].Comments++

        $prose = ($normalizedText -replace '<[^>]+>', ' ').Trim()
        if ([string]::IsNullOrWhiteSpace($prose)) {
            continue
        }

        if (Test-CommentedCode $prose) {
            Add-Violation $relativePath ($lineIndex + 1) "commented-code" $normalizedText
        }

        if ($prose -notmatch '[\u3400-\u9FFF]') {
            Add-Violation $relativePath ($lineIndex + 1) "language" $normalizedText
        }

        if ($prose -match '(\u3002|\.)\s*$') {
            Add-Violation $relativePath ($lineIndex + 1) "period" $normalizedText
        }
    }
}

$files = Get-ChildItem -LiteralPath $sourceRoot -Recurse -File -Filter '*.cs' |
    Where-Object { -not (Test-ExcludedPath $_) } |
    Sort-Object FullName

foreach ($file in $files) {
    Read-CSharpFile $file
}

$denominator = $commentLines + $codeLines
$commentRate = if ($denominator -eq 0) { 0 } else { [math]::Round($commentLines * 100.0 / $denominator, 2) }

Write-Host "Comment style check"
Write-Host "Files: $scannedFiles"
Write-Host "Comment lines: $commentLines"
Write-Host "Code lines: $codeLines"
Write-Host "Comment rate: $commentRate% (minimum $MinimumRate%, recommended $RecommendedRate%)"
Write-Host ""
Write-Host "Module rates"

foreach ($entry in $moduleStats.GetEnumerator() | Sort-Object Name) {
    $moduleDenominator = $entry.Value.Comments + $entry.Value.Code
    $moduleRate = if ($moduleDenominator -eq 0) { 0 } else { [math]::Round($entry.Value.Comments * 100.0 / $moduleDenominator, 2) }
    Write-Host ("{0,-20} {1,6}%  comments {2,5}  code {3,5}" -f $entry.Name, $moduleRate, $entry.Value.Comments, $entry.Value.Code)
}

if ($violations.Count -gt 0) {
    Write-Host ""
    Write-Host "Violations: $($violations.Count)"
    foreach ($violation in $violations) {
        Write-Host ("[{0}] {1}:{2} {3}" -f $violation.Rule, $violation.Path, $violation.Line, $violation.Text)
    }
}

$failed = $commentRate -lt $MinimumRate -or $violations.Count -gt 0
if ($failed -and -not $NoFail) {
    exit 1
}

exit 0
